import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'en' | 'tr';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  en: {
    'nav.products': 'Products',
    'nav.categories': 'Categories',
    'nav.orders': 'Orders',
    'nav.profile': 'Profile',
    'nav.admin': 'Admin Panel',
    'nav.cart': 'Cart',
    'hero.title': 'Premium Streetwear',
    'hero.subtitle': 'Maximum Drip',
    'hero.description': "Elevate your style with our exclusive collection of black-themed streetwear. From hoodies to complete outfits, we've got your drip covered.",
    'hero.shopNow': 'Shop Now',
    'hero.browseCategories': 'Browse Categories',
    'featured.title': 'Featured Collection',
    'featured.subtitle': 'Handpicked pieces for the ultimate street style',
    'featured.viewAll': 'View All Products',
    'footer.tagline': 'Premium streetwear for those who know.',
    'footer.shop': 'Shop',
    'footer.allProducts': 'All Products',
    'footer.categories': 'Categories',
    'footer.account': 'Account',
    'footer.profile': 'Profile',
    'footer.orders': 'Orders',
    'footer.info': 'Info',
    'footer.shipping': 'Shipping & Returns',
    'footer.privacy': 'Privacy Policy',
    'footer.terms': 'Terms of Service',
    'footer.rights': 'All rights reserved.',
    'footer.madeBy': 'Made by',
    'product.addToCart': 'Add to Cart',
    'product.outOfStock': 'Out of Stock',
    'product.inStock': 'In Stock',
    'product.stock': 'Stock',
    'product.notFound': 'Product Not Found',
    'product.notFoundDescription': "The product you're looking for doesn't exist.",
    'product.addedToCart': 'Added to cart!',
    'product.lowStock': 'Low Stock',
    'product.remaining': 'remaining',
    'product.category': 'Category',
    'product.description': 'Description',
    'cart.title': 'Shopping Cart',
    'cart.empty': 'Your cart is empty',
    'cart.continueShopping': 'Continue Shopping',
    'cart.item': 'Item',
    'cart.price': 'Price',
    'cart.quantity': 'Quantity',
    'cart.total': 'Total',
    'cart.subtotal': 'Subtotal',
    'cart.proceedToCheckout': 'Proceed to Checkout',
    'cart.remove': 'Remove',
    'cart.itemRemoved': 'Item removed from cart',
    'cart.quantityUpdated': 'Quantity updated',
    'cart.insufficientStock': 'Insufficient stock',
    'checkout.title': 'Checkout',
    'checkout.shippingInfo': 'Shipping Information',
    'checkout.fullName': 'Full Name',
    'checkout.email': 'Email',
    'checkout.address': 'Address',
    'checkout.city': 'City',
    'checkout.postalCode': 'Postal Code',
    'checkout.country': 'Country',
    'checkout.orderSummary': 'Order Summary',
    'checkout.subtotal': 'Subtotal',
    'checkout.shipping': 'Shipping',
    'checkout.free': 'Free',
    'checkout.total': 'Total',
    'checkout.placeOrder': 'Place Order',
    'checkout.processing': 'Processing...',
    'checkout.signInRequired': 'Please sign in to continue with checkout.',
    'checkout.emptyCartDescription': 'Add some items to your cart before checking out.',
    'checkout.backToCart': 'Back to Cart',
    'orders.title': 'My Orders',
    'orders.noOrders': 'No orders yet',
    'orders.orderNumber': 'Order',
    'orders.date': 'Date',
    'orders.total': 'Total',
    'orders.status': 'Status',
    'orders.items': 'Items',
    'orders.viewDetails': 'View Details',
    'orders.signInRequired': 'Please sign in to view your orders.',
    'orders.noOrdersDescription': 'Start shopping to create your first order.',
    'orders.status.pending': 'Pending',
    'orders.status.processing': 'Processing',
    'orders.status.shipped': 'Shipped',
    'orders.status.delivered': 'Delivered',
    'orders.status.cancelled': 'Cancelled',
    'profile.title': 'My Profile',
    'profile.accountInfo': 'Account Information',
    'profile.name': 'Name',
    'profile.email': 'Email',
    'profile.memberSince': 'Member Since',
    'profile.recentOrders': 'Recent Orders',
    'profile.viewAllOrders': 'View All Orders',
    'profile.adminPanel': 'Admin Panel',
    'profile.logout': 'Logout',
    'profile.signInRequired': 'Please sign in to view your profile.',
    'profile.logoutSuccess': 'Logged out successfully',
    'profile.logoutError': 'Failed to logout',
    'profile.adminAccess': 'You have administrator access to manage the store.',
    'admin.products': 'Products',
    'admin.orders': 'Orders',
    'admin.settings': 'Settings',
    'admin.dashboard': 'Dashboard',
    'admin.welcome': 'Welcome to EwoDrip Admin Panel',
    'admin.totalRevenue': 'Total Revenue',
    'admin.fromOrders': 'From {count} orders',
    'admin.totalOrders': 'Total Orders',
    'admin.activeProducts': 'Active products',
    'admin.customers': 'Customers',
    'admin.uniqueCustomers': 'Unique customers',
    'admin.recentOrders': 'Recent Orders',
    'admin.addProduct': 'Add Product',
    'admin.editProduct': 'Edit Product',
    'admin.deleteProduct': 'Delete Product',
    'admin.productName': 'Product Name',
    'admin.productDescription': 'Description',
    'admin.productPrice': 'Price',
    'admin.productStock': 'Stock',
    'admin.productCategory': 'Category',
    'admin.productImages': 'Images',
    'admin.uploadImages': 'Upload Images',
    'admin.save': 'Save',
    'admin.cancel': 'Cancel',
    'admin.delete': 'Delete',
    'admin.edit': 'Edit',
    'admin.actions': 'Actions',
    'admin.orderDetails': 'Order Details',
    'admin.updateStatus': 'Update Status',
    'admin.shippingSettings': 'Shipping Settings',
    'admin.shippingFee': 'Shipping Fee',
    'admin.freeShippingThreshold': 'Free Shipping Threshold',
    'admin.stripeSettings': 'Stripe Settings',
    'admin.stripePublishableKey': 'Stripe Publishable Key',
    'admin.stripeSecretKey': 'Stripe Secret Key',
    'categories.title': 'Categories',
    'categories.allCategories': 'All Categories',
    'categories.filters': 'Filters',
    'categories.priceRange': 'Price Range',
    'categories.stockStatus': 'Stock Status',
    'categories.inStock': 'In Stock',
    'categories.outOfStock': 'Out of Stock',
    'categories.sortBy': 'Sort By',
    'categories.sortPriceLow': 'Price: Low to High',
    'categories.sortPriceHigh': 'Price: High to Low',
    'categories.sortNameAZ': 'Name: A-Z',
    'categories.sortNameZA': 'Name: Z-A',
    'categories.sortNewest': 'Newest First',
    'categories.noProducts': 'No products found',
    'categories.clearFilters': 'Clear Filters',
    'categories.minPrice': 'Min',
    'categories.maxPrice': 'Max',
    'search.placeholder': 'Search products...',
    'search.noResults': 'No results found',
    'auth.login': 'Login',
    'auth.logout': 'Logout',
    'auth.welcome': 'Welcome',
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.success': 'Success',
    'common.close': 'Close',
    'common.back': 'Back',
    'common.next': 'Next',
    'common.previous': 'Previous',
    'common.submit': 'Submit',
    'common.confirm': 'Confirm',
    'common.language': 'Language',
    'common.required': 'Required',
    'cart.signInRequired': 'Please sign in to view your shopping cart.',
    'cart.emptyDescription': 'Add some items to your cart to get started.',
    'cart.calculatedAtCheckout': 'Calculated at checkout',
    'cart.taxesCalculated': 'Taxes and shipping calculated at checkout',
  },
  tr: {
    'nav.products': 'Ürünler',
    'nav.categories': 'Kategoriler',
    'nav.orders': 'Siparişler',
    'nav.profile': 'Profil',
    'nav.admin': 'Yönetim Paneli',
    'nav.cart': 'Sepet',
    'hero.title': 'Premium Streetwear',
    'hero.subtitle': 'Maximum Drip',
    'hero.description': 'Siyah temalı özel streetwear koleksiyonumuzla tarzınızı yükseltin. Sweatshirt\'lerden komple kıyafetlere kadar, stilinizi tamamlıyoruz.',
    'hero.shopNow': 'Alışverişe Başla',
    'hero.browseCategories': 'Kategorilere Göz At',
    'featured.title': 'Öne Çıkan Koleksiyon',
    'featured.subtitle': 'Sokak stili için özenle seçilmiş parçalar',
    'featured.viewAll': 'Tüm Ürünleri Görüntüle',
    'footer.tagline': 'Bilenler için premium streetwear.',
    'footer.shop': 'Alışveriş',
    'footer.allProducts': 'Tüm Ürünler',
    'footer.categories': 'Kategoriler',
    'footer.account': 'Hesap',
    'footer.profile': 'Profil',
    'footer.orders': 'Siparişler',
    'footer.info': 'Bilgi',
    'footer.shipping': 'Kargo & İade',
    'footer.privacy': 'Gizlilik Politikası',
    'footer.terms': 'Kullanım Şartları',
    'footer.rights': 'Tüm hakları saklıdır.',
    'footer.madeBy': 'Yapımcı',
    'product.addToCart': 'Sepete Ekle',
    'product.outOfStock': 'Stokta Yok',
    'product.inStock': 'Stokta Var',
    'product.stock': 'Stok',
    'product.notFound': 'Ürün Bulunamadı',
    'product.notFoundDescription': 'Aradığınız ürün mevcut değil.',
    'product.addedToCart': 'Sepete eklendi!',
    'product.lowStock': 'Düşük Stok',
    'product.remaining': 'kaldı',
    'product.category': 'Kategori',
    'product.description': 'Açıklama',
    'cart.title': 'Alışveriş Sepeti',
    'cart.empty': 'Sepetiniz boş',
    'cart.continueShopping': 'Alışverişe Devam Et',
    'cart.item': 'Ürün',
    'cart.price': 'Fiyat',
    'cart.quantity': 'Adet',
    'cart.total': 'Toplam',
    'cart.subtotal': 'Ara Toplam',
    'cart.proceedToCheckout': 'Ödemeye Geç',
    'cart.remove': 'Kaldır',
    'cart.itemRemoved': 'Ürün sepetten kaldırıldı',
    'cart.quantityUpdated': 'Adet güncellendi',
    'cart.insufficientStock': 'Yetersiz stok',
    'checkout.title': 'Ödeme',
    'checkout.shippingInfo': 'Teslimat Bilgileri',
    'checkout.fullName': 'Ad Soyad',
    'checkout.email': 'E-posta',
    'checkout.address': 'Adres',
    'checkout.city': 'Şehir',
    'checkout.postalCode': 'Posta Kodu',
    'checkout.country': 'Ülke',
    'checkout.orderSummary': 'Sipariş Özeti',
    'checkout.subtotal': 'Ara Toplam',
    'checkout.shipping': 'Kargo',
    'checkout.free': 'Ücretsiz',
    'checkout.total': 'Toplam',
    'checkout.placeOrder': 'Siparişi Tamamla',
    'checkout.processing': 'İşleniyor...',
    'checkout.signInRequired': 'Ödeme işlemine devam etmek için lütfen giriş yapın.',
    'checkout.emptyCartDescription': 'Ödeme yapmadan önce sepetinize ürün ekleyin.',
    'checkout.backToCart': 'Sepete Dön',
    'orders.title': 'Siparişlerim',
    'orders.noOrders': 'Henüz sipariş yok',
    'orders.orderNumber': 'Sipariş',
    'orders.date': 'Tarih',
    'orders.total': 'Toplam',
    'orders.status': 'Durum',
    'orders.items': 'Ürünler',
    'orders.viewDetails': 'Detayları Görüntüle',
    'orders.signInRequired': 'Siparişlerinizi görüntülemek için lütfen giriş yapın.',
    'orders.noOrdersDescription': 'İlk siparişinizi oluşturmak için alışverişe başlayın.',
    'orders.status.pending': 'Beklemede',
    'orders.status.processing': 'İşleniyor',
    'orders.status.shipped': 'Kargoda',
    'orders.status.delivered': 'Teslim Edildi',
    'orders.status.cancelled': 'İptal Edildi',
    'profile.title': 'Profilim',
    'profile.accountInfo': 'Hesap Bilgileri',
    'profile.name': 'Ad',
    'profile.email': 'E-posta',
    'profile.memberSince': 'Üyelik Tarihi',
    'profile.recentOrders': 'Son Siparişler',
    'profile.viewAllOrders': 'Tüm Siparişleri Görüntüle',
    'profile.adminPanel': 'Yönetim Paneli',
    'profile.logout': 'Çıkış Yap',
    'profile.signInRequired': 'Profilinizi görüntülemek için lütfen giriş yapın.',
    'profile.logoutSuccess': 'Başarıyla çıkış yapıldı',
    'profile.logoutError': 'Çıkış yapılamadı',
    'profile.adminAccess': 'Mağazayı yönetmek için yönetici erişiminiz var.',
    'admin.products': 'Ürünler',
    'admin.orders': 'Siparişler',
    'admin.settings': 'Ayarlar',
    'admin.dashboard': 'Kontrol Paneli',
    'admin.welcome': 'EwoDrip Yönetim Paneline Hoş Geldiniz',
    'admin.totalRevenue': 'Toplam Gelir',
    'admin.fromOrders': '{count} siparişten',
    'admin.totalOrders': 'Toplam Siparişler',
    'admin.activeProducts': 'Aktif ürünler',
    'admin.customers': 'Müşteriler',
    'admin.uniqueCustomers': 'Benzersiz müşteriler',
    'admin.recentOrders': 'Son Siparişler',
    'admin.addProduct': 'Ürün Ekle',
    'admin.editProduct': 'Ürünü Düzenle',
    'admin.deleteProduct': 'Ürünü Sil',
    'admin.productName': 'Ürün Adı',
    'admin.productDescription': 'Açıklama',
    'admin.productPrice': 'Fiyat',
    'admin.productStock': 'Stok',
    'admin.productCategory': 'Kategori',
    'admin.productImages': 'Görseller',
    'admin.uploadImages': 'Görsel Yükle',
    'admin.save': 'Kaydet',
    'admin.cancel': 'İptal',
    'admin.delete': 'Sil',
    'admin.edit': 'Düzenle',
    'admin.actions': 'İşlemler',
    'admin.orderDetails': 'Sipariş Detayları',
    'admin.updateStatus': 'Durumu Güncelle',
    'admin.shippingSettings': 'Kargo Ayarları',
    'admin.shippingFee': 'Kargo Ücreti',
    'admin.freeShippingThreshold': 'Ücretsiz Kargo Limiti',
    'admin.stripeSettings': 'Stripe Ayarları',
    'admin.stripePublishableKey': 'Stripe Publishable Key',
    'admin.stripeSecretKey': 'Stripe Secret Key',
    'categories.title': 'Kategoriler',
    'categories.allCategories': 'Tüm Kategoriler',
    'categories.filters': 'Filtreler',
    'categories.priceRange': 'Fiyat Aralığı',
    'categories.stockStatus': 'Stok Durumu',
    'categories.inStock': 'Stokta Var',
    'categories.outOfStock': 'Stokta Yok',
    'categories.sortBy': 'Sırala',
    'categories.sortPriceLow': 'Fiyat: Düşükten Yükseğe',
    'categories.sortPriceHigh': 'Fiyat: Yüksekten Düşüğe',
    'categories.sortNameAZ': 'İsim: A-Z',
    'categories.sortNameZA': 'İsim: Z-A',
    'categories.sortNewest': 'En Yeniler',
    'categories.noProducts': 'Ürün bulunamadı',
    'categories.clearFilters': 'Filtreleri Temizle',
    'categories.minPrice': 'Min',
    'categories.maxPrice': 'Maks',
    'search.placeholder': 'Ürün ara...',
    'search.noResults': 'Sonuç bulunamadı',
    'auth.login': 'Giriş Yap',
    'auth.logout': 'Çıkış Yap',
    'auth.welcome': 'Hoş Geldiniz',
    'common.loading': 'Yükleniyor...',
    'common.error': 'Hata',
    'common.success': 'Başarılı',
    'common.close': 'Kapat',
    'common.back': 'Geri',
    'common.next': 'İleri',
    'common.previous': 'Önceki',
    'common.submit': 'Gönder',
    'common.confirm': 'Onayla',
    'common.language': 'Dil',
    'common.required': 'Gerekli',
    'cart.signInRequired': 'Sepetinizi görüntülemek için lütfen giriş yapın.',
    'cart.emptyDescription': 'Başlamak için sepetinize ürün ekleyin.',
    'cart.calculatedAtCheckout': 'Ödeme sırasında hesaplanacak',
    'cart.taxesCalculated': 'Vergiler ve kargo ödeme sırasında hesaplanacak',
  },
};

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('language');
    return (saved === 'tr' || saved === 'en') ? saved : 'en';
  });

  useEffect(() => {
    localStorage.setItem('language', language);
  }, [language]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
  };

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations['en']] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
}
